language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: fE2N6PkkWmER0JqDHRU6aA2KaoV5RazujK+TaBTyNxkC6kO5cdby3ya1KR5igZrS71k1JpG+4cSB9GMvvC0L9gR9gGUf64I/XuTOIUQ8heHc6axZ2D2P7RMkglwSzbpBs5wqyaQZJVnhEHs9O5/mhG67CiweFlDUiZ3y/OUZc1o=
  - secure: XbUDWITCjIWkb8Rt/Cs/02U+kDmGGGJgTja+mpQf/hwCMjUdUDT99PWVfolaJP4BoIRW9dPir4tVCrao/iGhpd8Q/2FOyALEJdgLEvZyO6bVpPlMpbdyLwCsBM4beWBEVHzxtcvRcbLOoqeLbhTVWKcCeZgfmUxsCXloOxRzN1w=
